name: KeyOverlay Build
on: [ push, pull_reqeust, workflow_dispatch ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x
      - name: Build
        run: dotnet build --configuration Release -o build/
      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: KeyOverlay-${{ matrix.os }}
          path: build/
